coal_retirement_fault_level_replacement_cost:
  sheet_name: "Power System Security"
  header_rows: 5
  end_row: 49
  column_range: "B:D"

efficient_level_of_system_strength_cost:
  sheet_name: "Power System Security"
  header_rows: 53
  end_row: 54
  column_range: "B:AE"

synchronous_unit_commitment_requirement_step_change&slow_growth:
  sheet_name: "Power System Security"
  header_rows: [59, 60]
  end_row: 72
  column_range: "B:G"

synchronous_unit_commitment_requirement_accelerated_transition:
  sheet_name: "Power System Security"
  header_rows: [75, 76]
  end_row: 88
  column_range: "B:G"
